name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TEST_BOARD: 'snowy_bb2'

jobs:
  changes-test:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    outputs:
      should-test: ${{ github.event_name == 'push' || steps.filter.outputs.src == 'true' }}
    steps:
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            src:
              - '.github/workflows/test.yml'
              - 'resources/**'
              - 'sdk/**'
              - 'src/**'
              - 'stored_apps/**'
              - 'tools/**'
              - 'third_party/**'
              - 'waftools/**'
              - 'waf'
              - 'wscript'

  build-test:
    needs: changes-test
    if: needs.changes-test.outputs.should-test == 'true'
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/pebble-dev/pebbleos-docker:v2
    steps:
      - name: Mark Github workspace as safe
        run: git config --system --add safe.directory "${GITHUB_WORKSPACE}" 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Python dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Configure
        run: ./waf configure --board ${{env.TEST_BOARD}}

      - name: Run tests
        run: ./waf test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: (!cancelled())
        with:
          report_paths: build/test/junit.xml
          annotate_only: true

      - name: Store failed test images
        uses: actions/upload-artifact@v4
        if: (!cancelled())
        with:
          name: failed_diff_images
          path: build/test/tests/failed/*-diff.png

  test-status:
    needs: [changes-test, build-test]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: needs.build-test.result == 'failure' || needs.build-test.result == 'cancelled'
        run: exit 1
